name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Echo
        run: echo ${{ env.TAG }}